# Generated by Django 3.1.5 on 2021-01-21 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='society',
            field=models.ManyToManyField(blank=True, to='societies.Society'),
        ),
    ]
