# Generated by Django 3.1.5 on 2021-01-22 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0002_dues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='society',
        ),
        migrations.DeleteModel(
            name='Dues',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Society',
        ),
    ]
