# Generated by Django 3.1.5 on 2021-01-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('societies', '0003_auto_20210122_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('contact', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=100)),
                ('society', models.ManyToManyField(blank=True, through='societies.Dues', to='societies.Society')),
            ],
        ),
        migrations.AddField(
            model_name='dues',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societies.member'),
        ),
        migrations.AddField(
            model_name='dues',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='societies.society'),
        ),
        migrations.AlterUniqueTogether(
            name='dues',
            unique_together={('member', 'society')},
        ),
    ]
